baseurl = "https://damienradtke.com/"
languageCode = "en-us"
title = "Version 7.0"

theme = "hyde"
PygmentsUseClasses = true
PygmentsCodeFences = true

[params]
description = "Occasional posts about programming."
