baseurl = "https://damienradtke.com/"
languageCode = "en-us"
title = "Version 7.0"

theme = "hyde"
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsStyle = "monokai"
pygmentsOptions = "nowrap=true"

# This is needed for deployment via Nomad, because it can't write to "resources" in the artifact directory.
resourceDir = "/tmp/resources"

[params]
description = "Fixes many known issues with version 6.0"

[[menu.main]]
identifier = "home"
name = "About"
url = "/pages/about"

[[menu.main]]
identifier = "github"
name = "Projects — Github"
url = "https://github.com/dradtke/"

[[menu.main]]
identifier = "sourcehut"
name = "Projects — Sourcehut"
url = "https://git.sr.ht/~damien"
